### ISSUE TITLE
新建模板项目出错

### ISSUE THREAD

**Issue by CloudnuY** [think-template/api#1]
![default](https://user-images.githubusercontent.com/14636247/32928343-7a0df6ea-cb8c-11e7-9967-224d0ba95855.png)

如图

若使用 `thinkjs new thinkjs-demo typescript` 则没有问题

**Comment by berwin** [comment]
@CloudnuY 清一下模板缓存试试呢？rm -rf ~/.think-templates

**Comment by CloudnuY** [comment]
@berwin 成功解决，多谢~
